"""
Intelligent Vulnerability Detection and Analysis Framework (IVDF)
Professional Report Generator — Production Ready
"""

import os
import json
import csv
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether, PageBreak
)
from reportlab.platypus.flowables import Flowable

# ─────────────────────────────────────────────
# Colour Palette
# ─────────────────────────────────────────────
DARK_BG        = colors.HexColor("#0D1117")
CARD_BG        = colors.HexColor("#161B22")
BORDER_COLOR   = colors.HexColor("#30363D")
ACCENT_BLUE    = colors.HexColor("#1F6FEB")
TEXT_PRIMARY   = colors.HexColor("#E6EDF3")
TEXT_SECONDARY = colors.HexColor("#8B949E")
WHITE          = colors.white

SEV_COLORS = {
    "CRITICAL": colors.HexColor("#DA3633"),
    "HIGH":     colors.HexColor("#D29922"),
    "MEDIUM":   colors.HexColor("#E3B341"),
    "LOW":      colors.HexColor("#388BFD"),
    "INFO":     colors.HexColor("#6E7681"),
}

SEV_BG = {
    "CRITICAL": colors.HexColor("#3D1F1F"),
    "HIGH":     colors.HexColor("#3D2F1F"),
    "MEDIUM":   colors.HexColor("#3D351F"),
    "LOW":      colors.HexColor("#1F2B3D"),
    "INFO":     colors.HexColor("#21262D"),
}


# ─────────────────────────────────────────────
# Custom Flowables
# ─────────────────────────────────────────────
class ColorBar(Flowable):
    """Full-width horizontal colour bar (used for header accent stripe)."""
    def __init__(self, color, height=4, width=None):
        super().__init__()
        self.bar_color = color
        self.bar_height = height
        self._width = width

    def wrap(self, availWidth, availHeight):
        self._avail = availWidth
        return (self._width or availWidth, self.bar_height)

    def draw(self):
        self.canv.setFillColor(self.bar_color)
        self.canv.rect(0, 0, self._width or self._avail, self.bar_height, fill=1, stroke=0)


class SeverityBadge(Flowable):
    """Inline coloured pill badge for severity labels."""
    def __init__(self, label, width=80, height=18):
        super().__init__()
        self.label = label.upper()
        self.badge_width = width
        self.badge_height = height

    def wrap(self, availWidth, availHeight):
        return (self.badge_width, self.badge_height)

    def draw(self):
        c = self.canv
        color = SEV_COLORS.get(self.label, colors.grey)
        bg    = SEV_BG.get(self.label, colors.HexColor("#21262D"))
        r = self.badge_height / 2
        c.setFillColor(bg)
        c.roundRect(0, 0, self.badge_width, self.badge_height, r, fill=1, stroke=0)
        c.setStrokeColor(color)
        c.setLineWidth(1)
        c.roundRect(0, 0, self.badge_width, self.badge_height, r, fill=0, stroke=1)
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(self.badge_width / 2, 5, self.label)


# ─────────────────────────────────────────────
# Page template helpers
# ─────────────────────────────────────────────
def _header_footer(canvas, doc):
    """Draw a dark header band and confidential footer on every page."""
    w, h = letter
    margin = 0.6 * inch

    # ── top accent stripe ──
    canvas.saveState()
    canvas.setFillColor(ACCENT_BLUE)
    canvas.rect(0, h - 4, w, 4, fill=1, stroke=0)

    # ── page number (top-right) ──
    canvas.setFillColor(TEXT_SECONDARY)
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - margin, h - 20, f"Page {doc.page}")

    # ── footer rule ──
    canvas.setStrokeColor(BORDER_COLOR)
    canvas.setLineWidth(0.5)
    canvas.line(margin, 36, w - margin, 36)

    canvas.setFillColor(TEXT_SECONDARY)
    canvas.setFont("Helvetica-Oblique", 8)
    footer = "CONFIDENTIAL — For authorised security assessment use only. " \
             "This report was generated by the Intelligent Vulnerability Detection and Analysis Framework."
    canvas.drawString(margin, 22, footer)
    canvas.restoreState()


# ─────────────────────────────────────────────
# Style factory
# ─────────────────────────────────────────────
def _build_styles():
    base = getSampleStyleSheet()

    def ps(name, **kw):
        return ParagraphStyle(name, **kw)

    return {
        "report_title": ps(
            "ReportTitle",
            fontName="Helvetica-Bold", fontSize=22,
            textColor=TEXT_PRIMARY, alignment=TA_CENTER,
            spaceAfter=4
        ),
        "report_subtitle": ps(
            "ReportSubtitle",
            fontName="Helvetica", fontSize=11,
            textColor=TEXT_SECONDARY, alignment=TA_CENTER,
            spaceAfter=2
        ),
        "section_heading": ps(
            "SectionHeading",
            fontName="Helvetica-Bold", fontSize=13,
            textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6,
            borderPad=(0, 0, 4, 0)
        ),
        "vuln_title": ps(
            "VulnTitle",
            fontName="Helvetica-Bold", fontSize=12,
            textColor=TEXT_PRIMARY, spaceAfter=2
        ),
        "label": ps(
            "Label",
            fontName="Helvetica-Bold", fontSize=9,
            textColor=TEXT_SECONDARY
        ),
        "value": ps(
            "Value",
            fontName="Helvetica", fontSize=9,
            textColor=TEXT_PRIMARY, leading=13
        ),
        "body": ps(
            "Body",
            fontName="Helvetica", fontSize=9,
            textColor=TEXT_PRIMARY, leading=14, spaceAfter=2
        ),
        "bullet": ps(
            "Bullet",
            fontName="Helvetica", fontSize=9,
            textColor=TEXT_PRIMARY, leading=14,
            leftIndent=12, spaceAfter=2, bulletIndent=0
        ),
        "tag_text": ps(
            "TagText",
            fontName="Helvetica-Bold", fontSize=8,
            textColor=ACCENT_BLUE
        ),
    }


# ─────────────────────────────────────────────
# Table builders
# ─────────────────────────────────────────────
def _scan_details_table(metadata: dict, styles: dict):
    """2-column bordered table for scan metadata."""
    label_map = {
        "target":    "Target",
        "scan_id":   "Scan ID",
        "scan_type": "Scan Type",
        "started":   "Started",
        "completed": "Completed",
        "duration":  "Duration",
        "risk_score":"Risk Score",
        "generated": "Generated",
    }
    rows = []
    for key, display in label_map.items():
        val = metadata.get(key, metadata.get(display, "—"))
        rows.append([
            Paragraph(display, styles["label"]),
            Paragraph(str(val), styles["value"]),
        ])

    col_w = [1.6 * inch, 5.2 * inch]
    tbl = Table(rows, colWidths=col_w, repeatRows=0)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), CARD_BG),
        ("ROWBACKGROUNDS",(0,0),(-1,-1),[CARD_BG, colors.HexColor("#1A2030")]),
        ("BOX",          (0, 0), (-1, -1), 0.75, BORDER_COLOR),
        ("INNERGRID",    (0, 0), (-1, -1), 0.5,  BORDER_COLOR),
        ("TOPPADDING",   (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
        ("LEFTPADDING",  (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return tbl


def _severity_table(summary: dict, styles: dict):
    """Severity summary table with coloured count cells."""
    order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    header = [Paragraph("<b>Severity</b>", styles["label"]),
              Paragraph("<b>Count</b>",    styles["label"])]
    rows = [header]
    for sev in order:
        count = summary.get(sev, summary.get(sev.title(), 0))
        color = SEV_COLORS.get(sev, TEXT_SECONDARY)
        rows.append([
            Paragraph(f'<font color="{color.hexval()}">{sev}</font>', styles["value"]),
            Paragraph(f'<font color="{color.hexval()}"><b>{count}</b></font>', styles["value"]),
        ])

    col_w = [3.4 * inch, 3.4 * inch]
    tbl = Table(rows, colWidths=col_w)
    style_cmds = [
        ("BACKGROUND",   (0, 0), (-1, 0),  ACCENT_BLUE),
        ("TEXTCOLOR",    (0, 0), (-1, 0),  WHITE),
        ("BACKGROUND",   (0, 1), (-1, -1), CARD_BG),
        ("ROWBACKGROUNDS",(0,1),(-1,-1),[CARD_BG, colors.HexColor("#1A2030")]),
        ("BOX",          (0, 0), (-1, -1), 0.75, BORDER_COLOR),
        ("INNERGRID",    (0, 0), (-1, -1), 0.5,  BORDER_COLOR),
        ("TOPPADDING",   (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 7),
        ("LEFTPADDING",  (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("ALIGN",        (1, 0), (1, -1),  "CENTER"),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ]
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def _vuln_card(idx: int, vuln: dict, styles: dict):
    """Build a self-contained vulnerability card as a KeepTogether block."""
    sev = vuln.get("severity", "INFO").upper()
    sev_color = SEV_COLORS.get(sev, TEXT_SECONDARY)
    sev_hex   = sev_color.hexval()

    elements = []

    # ── title row ──
    title_text = (
        f'<font color="#E6EDF3"><b>{idx}. {vuln.get("name", "Unknown Vulnerability")}</b></font>'
        f'    <font color="{sev_hex}" size="9"><b>[{sev}]</b></font>'
    )
    elements.append(Paragraph(title_text, styles["vuln_title"]))
    elements.append(ColorBar(sev_color, height=2))
    elements.append(Spacer(1, 6))

    # ── meta row (OWASP / CVSS / Affected) ──
    owasp    = vuln.get("owasp", "—")
    cvss     = vuln.get("cvss", vuln.get("cvss_score", "—"))
    affected = vuln.get("affected", vuln.get("port", vuln.get("url", "—")))

    meta_rows = [[
        Paragraph("<b>OWASP Mapping</b>",  styles["label"]),
        Paragraph(str(owasp), styles["value"]),
        Paragraph("<b>CVSS Score</b>",     styles["label"]),
        Paragraph(f'<font color="{sev_hex}"><b>{cvss}</b></font>', styles["value"]),
        Paragraph("<b>Affected</b>",       styles["label"]),
        Paragraph(str(affected), styles["value"]),
    ]]
    meta_tbl = Table(meta_rows, colWidths=[1.1*inch, 1.7*inch, 0.9*inch, 0.8*inch, 0.8*inch, 1.5*inch])
    meta_tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), colors.HexColor("#1A2030")),
        ("BOX",          (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("INNERGRID",    (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(meta_tbl)
    elements.append(Spacer(1, 8))

    # ── detail rows (explanation / impact / remediation / references) ──
    detail_data = []

    def add_section(heading, content):
        if not content:
            return
        if isinstance(content, list):
            body_para = Paragraph(
                "".join(f"&bull;  {item}<br/>" for item in content),
                styles["bullet"]
            )
        else:
            body_para = Paragraph(str(content), styles["body"])
        detail_data.append([
            Paragraph(f"<b>{heading}</b>", styles["label"]),
            body_para,
        ])

    add_section("Explanation",  vuln.get("explanation", vuln.get("description", "")))
    add_section("Impact",       vuln.get("impact", ""))
    add_section("Remediation",  vuln.get("remediation", vuln.get("fix", [])))
    add_section("References",   vuln.get("references", vuln.get("refs", "")))

    if detail_data:
        det_tbl = Table(detail_data, colWidths=[1.1*inch, 5.7*inch])
        det_tbl.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, -1), CARD_BG),
            ("ROWBACKGROUNDS",(0,0),(-1,-1),[CARD_BG, colors.HexColor("#1A2030")]),
            ("BOX",          (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("INNERGRID",    (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ("TOPPADDING",   (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 7),
            ("LEFTPADDING",  (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(det_tbl)

    elements.append(Spacer(1, 14))
    return KeepTogether(elements)


# ─────────────────────────────────────────────
# ReportGenerator
# ─────────────────────────────────────────────
class ReportGenerator:
    """
    IVDF Report Generator — supports PDF, JSON, CSV output.

    Usage
    -----
    rg = ReportGenerator()
    rg.generate_pdf("my_report", data)
    rg.generate_json("my_report", data)
    rg.generate_csv("my_report", data)

    data schema
    -----------
    {
        "metadata": {
            "target":     "127.0.0.1",
            "scan_id":    "913ee222-...",
            "scan_type":  "normal",
            "started":    "2026-05-24T09:37:13",
            "completed":  "2026-05-24T09:40:44",
            "duration":   "211.4s",
            "risk_score": 9.8,
            "generated":  "2026-05-24 09:45 UTC",
        },
        "severity_summary": {
            "CRITICAL": 1, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0
        },
        "vulnerabilities": [
            {
                "name":        "Dangerous Open Port: 445/SMB",
                "severity":    "CRITICAL",
                "owasp":       "OWASP A06:2021 – Security Misconfiguration",
                "cvss":        9.8,
                "affected":    "445",
                "explanation": "Port 445 (SMB) is exposed to the network.",
                "impact":      "EternalBlue / WannaCry attack surface.",
                "remediation": [
                    "Close port 445 if the service is not required.",
                    "Restrict access via firewall rules to trusted IPs only.",
                    "Place the service behind a VPN or bastion host.",
                    "Enable authentication and encryption for the service.",
                ],
                "references":  "CVE-2017-0144 | MS17-010",
            }
        ],
    }
    """

    OUTPUT_DIR = "generated_reports"

    def _ensure_dir(self):
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)

    # ── PDF ───────────────────────────────────
    def generate_pdf(self, filename: str, data: dict) -> str:
        self._ensure_dir()
        filepath = os.path.join(self.OUTPUT_DIR, f"{filename}.pdf")
        styles   = _build_styles()

        doc = SimpleDocTemplate(
            filepath,
            pagesize=letter,
            leftMargin=0.6 * inch,
            rightMargin=0.6 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            title="Vulnerability Assessment Report",
            author="IVDF",
        )

        story = []

        # ── COVER / TITLE ──────────────────────────────
        story.append(Spacer(1, 20))
        story.append(Paragraph("Vulnerability Assessment Report", styles["report_title"]))
        story.append(Paragraph(
            "Intelligent Vulnerability Detection and Analysis Framework",
            styles["report_subtitle"]
        ))
        story.append(Spacer(1, 4))
        story.append(HRFlowable(
            width="100%", thickness=1, color=BORDER_COLOR, spaceAfter=18
        ))

        # ── SCAN DETAILS ───────────────────────────────
        story.append(Paragraph("Scan Details", styles["section_heading"]))
        story.append(_scan_details_table(data.get("metadata", {}), styles))
        story.append(Spacer(1, 18))

        # ── SEVERITY SUMMARY ───────────────────────────
        story.append(Paragraph("Severity Summary", styles["section_heading"]))
        story.append(_severity_table(data.get("severity_summary", {}), styles))
        story.append(Spacer(1, 18))

        # ── VULNERABILITY FINDINGS ─────────────────────
        vulns = data.get("vulnerabilities", [])
        if vulns:
            story.append(HRFlowable(
                width="100%", thickness=0.5, color=BORDER_COLOR, spaceAfter=10
            ))
            story.append(Paragraph("Vulnerability Findings", styles["section_heading"]))
            for idx, vuln in enumerate(vulns, start=1):
                story.append(_vuln_card(idx, vuln, styles))

        # ── BUILD ──────────────────────────────────────
        doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
        return filepath

    # ── JSON ──────────────────────────────────
    def generate_json(self, filename: str, data: dict) -> str:
        self._ensure_dir()
        filepath = os.path.join(self.OUTPUT_DIR, f"{filename}.json")
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, default=str)
        return filepath

    # ── CSV ───────────────────────────────────
    def generate_csv(self, filename: str, data: dict) -> str:
        self._ensure_dir()
        filepath = os.path.join(self.OUTPUT_DIR, f"{filename}.csv")

        metadata = data.get("metadata", {})
        summary  = data.get("severity_summary", {})
        vulns    = data.get("vulnerabilities", [])

        fieldnames = [
            "scan_target", "scan_id", "scan_type", "started", "completed",
            "duration", "risk_score", "generated",
            "vuln_index", "name", "severity", "owasp", "cvss",
            "affected", "explanation", "impact", "remediation", "references",
        ]

        rows = []
        for idx, vuln in enumerate(vulns, start=1):
            fix = vuln.get("remediation", vuln.get("fix", []))
            if isinstance(fix, list):
                fix = " | ".join(fix)
            rows.append({
                "scan_target":  metadata.get("target",     ""),
                "scan_id":      metadata.get("scan_id",    ""),
                "scan_type":    metadata.get("scan_type",  ""),
                "started":      metadata.get("started",    ""),
                "completed":    metadata.get("completed",  ""),
                "duration":     metadata.get("duration",   ""),
                "risk_score":   metadata.get("risk_score", ""),
                "generated":    metadata.get("generated",  ""),
                "vuln_index":   idx,
                "name":         vuln.get("name",        ""),
                "severity":     vuln.get("severity",    ""),
                "owasp":        vuln.get("owasp",       ""),
                "cvss":         vuln.get("cvss",        vuln.get("cvss_score", "")),
                "affected":     vuln.get("affected",    vuln.get("port", "")),
                "explanation":  vuln.get("explanation", vuln.get("description", "")),
                "impact":       vuln.get("impact",      ""),
                "remediation":  fix,
                "references":   vuln.get("references",  ""),
            })

        if not rows:
            rows.append({k: "" for k in fieldnames})

        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)

        return filepath


# ─────────────────────────────────────────────
# Demo / smoke test
# ─────────────────────────────────────────────
if __name__ == "__main__":
    sample_data = {
        "metadata": {
            "target":     "127.0.0.1",
            "scan_id":    "913ee222-2a55-4ca4-9475-88db28ccf774",
            "scan_type":  "normal",
            "started":    "2026-05-24T09:37:13.248880",
            "completed":  "2026-05-24T09:40:44.741772",
            "duration":   "211.4s",
            "risk_score": 9.8,
            "generated":  "2026-05-24 09:45 UTC",
        },
        "severity_summary": {
            "CRITICAL": 1,
            "HIGH":     0,
            "MEDIUM":   0,
            "LOW":      0,
            "INFO":     0,
        },
        "vulnerabilities": [
            {
                "name":        "Dangerous Open Port: 445/SMB",
                "severity":    "CRITICAL",
                "owasp":       "OWASP A06:2021 \u2013 Security Misconfiguration",
                "cvss":        9.8,
                "affected":    "445",
                "explanation": (
                    "Port 445 (SMB) is exposed to the network without "
                    "firewall restrictions. This service allows remote file "
                    "sharing and is a frequent target for automated exploits."
                ),
                "impact": "EternalBlue / WannaCry attack surface.",
                "remediation": [
                    "Close port 445 if the service is not required.",
                    "Restrict access via firewall rules to trusted IPs only.",
                    "Place the service behind a VPN or bastion host.",
                    "Enable authentication and encryption for the service.",
                ],
                "references": "CVE-2017-0144 | MS17-010",
            },
        ],
    }

    rg = ReportGenerator()
    pdf_path  = rg.generate_pdf ("report_913ee222_demo", sample_data)
    json_path = rg.generate_json("report_913ee222_demo", sample_data)
    csv_path  = rg.generate_csv ("report_913ee222_demo", sample_data)

    print(f"PDF  → {pdf_path}")
    print(f"JSON → {json_path}")
    print(f"CSV  → {csv_path}")